#!/usr/bin/env python3
"""Generate the compiled ML-DSA-44 startup KAT from pinned Wycheproof JSON."""

import argparse
import hashlib
import json
from pathlib import Path


SOURCE_COMMIT = "6d7cccd0fcb1917368579adeeac10fe802f1b521"
SOURCE_SHA256 = "5ec04790c240c443ca8b662b8fc871834602c7cce87fcd36a193110745b2b9ea"
SOURCE_PATH = "testvectors_v1/mldsa_44_verify_test.json"


def quoted_hex(name: str, value: str) -> list[str]:
    lines = [f"inline constexpr char {name}[] ="]
    for offset in range(0, len(value), 96):
        lines.append(f'    "{value[offset:offset + 96]}"')
    lines[-1] += ";"
    return lines


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("json", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    raw = args.json.read_bytes()
    actual_sha256 = hashlib.sha256(raw).hexdigest()
    if actual_sha256 != SOURCE_SHA256:
        raise SystemExit(f"unexpected source SHA-256: {actual_sha256}")
    document = json.loads(raw)
    if document.get("algorithm") != "ML-DSA-44":
        raise SystemExit("unexpected algorithm")

    group = document["testGroups"][0]
    tests = {test["tcId"]: test for test in group["tests"]}
    valid = tests[20]
    noncanonical = tests[15]
    if valid["result"] != "valid" or "ValidSignature" not in valid["flags"]:
        raise SystemExit("tcId 20 is no longer the expected positive vector")
    if noncanonical["result"] != "invalid" or "InvalidHintsEncoding" not in noncanonical["flags"]:
        raise SystemExit("tcId 15 is no longer the expected negative vector")

    vectors = {
        "PUBLIC_KEY_HEX": group["publicKey"],
        "VALID_MESSAGE_HEX": valid["msg"],
        "VALID_SIGNATURE_HEX": valid["sig"],
        "NONCANONICAL_MESSAGE_HEX": noncanonical["msg"],
        "NONCANONICAL_SIGNATURE_HEX": noncanonical["sig"],
    }
    expected_bytes = {
        "PUBLIC_KEY_HEX": 1312,
        "VALID_MESSAGE_HEX": 32,
        "VALID_SIGNATURE_HEX": 2420,
        "NONCANONICAL_MESSAGE_HEX": 32,
        "NONCANONICAL_SIGNATURE_HEX": 2420,
    }
    for name, value in vectors.items():
        if len(value) != 2 * expected_bytes[name]:
            raise SystemExit(f"unexpected {name} length")

    lines = [
        "// Generated by contrib/devtools/gen-mldsa44-kat.py; do not edit.",
        f"// C2SP/Wycheproof commit: {SOURCE_COMMIT}",
        f"// Source: {SOURCE_PATH}",
        f"// Source SHA-256: {SOURCE_SHA256}",
        "#ifndef BLACKCOIN_CRYPTO_MLDSA_KAT_H",
        "#define BLACKCOIN_CRYPTO_MLDSA_KAT_H",
        "",
        "namespace mldsa_kat {",
        "",
    ]
    for name, value in vectors.items():
        lines.extend(quoted_hex(name, value.lower()))
        lines.append("")
    lines.extend([
        "} // namespace mldsa_kat",
        "",
        "#endif // BLACKCOIN_CRYPTO_MLDSA_KAT_H",
        "",
    ])
    args.output.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
