// Copyright (c) 2012-2022 Blackcoin Core Developers
// Copyright (c) 2012-2022 Blackcoin More Developers
// Copyright (c) 2012-2022 Blackcoin Developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#include <clientversion.h>
#include <util/translation.h>

#include <tinyformat.h>

#include <algorithm>
#include <cctype>
#include <sstream>
#include <string>
#include <vector>

/**
 * Name of client reported in the 'version' message. Report the same name
 * for both blackcoind and blackcoin-qt, to make it harder for attackers to
 * target servers or GUI users specifically.
 */
const std::string CLIENT_NAME("Blackcoin");


#ifdef HAVE_BUILD_INFO
#include <obj/build.h>
// The <obj/build.h>, which is generated by the build environment (share/genbuild.sh),
// could contain only one line of the following:
//   - "#define BUILD_GIT_TAG ...", if the top commit is tagged
//   - "#define BUILD_GIT_COMMIT ...", if the top commit is not tagged
//   - "// No build information available", if proper git information is not available
#endif

//! git archive substitutes the full source commit on the next line.
#define GIT_COMMIT_ID "$Format:%H$"

#ifdef BUILD_SOURCE_COMMIT
    #define SOURCE_COMMIT_ID BUILD_SOURCE_COMMIT
#else
    #define SOURCE_COMMIT_ID GIT_COMMIT_ID
#endif

#ifdef BUILD_SOURCE_DIRTY
    #define SOURCE_TREE_DIRTY (BUILD_SOURCE_DIRTY != 0)
#else
    // A git archive is an immutable tree. A normal build with git metadata
    // always receives BUILD_SOURCE_DIRTY from share/genbuild.sh.
    #define SOURCE_TREE_DIRTY false
#endif

#ifdef BUILD_GIT_TAG
    #define BUILD_DESC BUILD_GIT_TAG
    #define BUILD_SUFFIX ""
#else
    #define BUILD_DESC "v" PACKAGE_VERSION
    #if CLIENT_VERSION_IS_RELEASE
        #define BUILD_SUFFIX ""
    #elif defined(BUILD_GIT_COMMIT)
        #define BUILD_SUFFIX "-" BUILD_GIT_COMMIT
    #elif defined(GIT_COMMIT_ID)
        #define BUILD_SUFFIX "-g" GIT_COMMIT_ID
    #else
        #define BUILD_SUFFIX "-unk"
    #endif
#endif

static std::string FormatVersion(int nVersion)
{
    return strprintf("%d.%d.%d", nVersion / 10000, (nVersion / 100) % 100, nVersion % 100);
}

std::string FormatFullVersion()
{
    static const std::string CLIENT_BUILD(BUILD_DESC BUILD_SUFFIX);
    return CLIENT_BUILD;
}

std::string FormatSourceCommit()
{
    static const std::string source_commit{SOURCE_COMMIT_ID};
    if (source_commit.size() != 40 ||
        !std::all_of(source_commit.begin(), source_commit.end(), [](unsigned char character) {
            return std::isdigit(character) ||
                   (character >= 'a' && character <= 'f');
        })) {
        return {};
    }
    return source_commit;
}

bool IsSourceTreeDirty()
{
    return SOURCE_TREE_DIRTY;
}

std::string FormatSourceIdentity()
{
    const std::string source_commit = FormatSourceCommit();
    if (source_commit.empty()) return "Source commit: unavailable";
    return strprintf("Source commit: %s%s", source_commit,
                     IsSourceTreeDirty() ? " (dirty)" : "");
}

/**
 * Format the subversion field according to BIP 14 spec (https://github.com/bitcoin/bips/blob/master/bip-0014.mediawiki)
 */
std::string FormatSubVersion(const std::string& name, int nClientVersion, const std::vector<std::string>& comments)
{
    std::ostringstream ss;
    ss << "/";
    ss << name << ":" << FormatVersion(nClientVersion);
    if (!comments.empty())
    {
        std::vector<std::string>::const_iterator it(comments.begin());
        ss << "(" << *it;
        for(++it; it != comments.end(); ++it)
            ss << "; " << *it;
        ss << ")";
    }
    ss << "/";
    return ss.str();
}

std::string CopyrightHolders(const std::string& strPrefix)
{
    std::string strCopyrightHolders =
        strPrefix + "Quantum Quasar Developers" +
        "\n" + strPrefix + "Blackcoin Core Developers" +
        "\n" + strPrefix + "Blackcoin More Developers" +
        "\n" + strPrefix + "Blackcoin Developers";
    return strCopyrightHolders;
}

std::string LicenseInfo()
{
    const std::string URL_SOURCE_CODE = "<https://github.com/Blackcoin-Dev/Blackcoin>";

    return strprintf(_("Copyright (C) 2024-%i Quantum Quasar Developers\n"
                       "Copyright (C) 2009-%i Blackcoin Core Developers\n"
                       "Copyright (C) 2018-%i Blackcoin More Developers\n"
                       "Copyright (C) 2014-%i Blackcoin Developers").translated,
                     COPYRIGHT_YEAR, COPYRIGHT_YEAR, COPYRIGHT_YEAR, COPYRIGHT_YEAR) +
           "\n" +
           strprintf(_("Please contribute if you find %s useful. "
                       "Visit %s for further information about the software.").translated, PACKAGE_NAME, "<" PACKAGE_URL ">") +
           "\n" +
           strprintf(_("The source code is available from %s.").translated, URL_SOURCE_CODE) +
           "\n" +
           "\n" +
           _("This is experimental software.").translated + "\n" +
           strprintf(_("Distributed under the MIT software license, see the accompanying file %s or %s").translated, "COPYING", "<https://opensource.org/licenses/MIT>") +
           "\n";
}
